/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as ThreatMapRouteImport } from './routes/threat-map'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OutilsRouteImport } from './routes/outils'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IrisRouteImport } from './routes/iris'
import { Route as IocsRouteImport } from './routes/iocs'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as FacturationRouteImport } from './routes/facturation'
import { Route as DeploiementRouteImport } from './routes/deploiement'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AlertesRouteImport } from './routes/alertes'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ClientsNewRouteImport } from './routes/clients.new'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'

const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatMapRoute = ThreatMapRouteImport.update({
  id: '/threat-map',
  path: '/threat-map',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OutilsRoute = OutilsRouteImport.update({
  id: '/outils',
  path: '/outils',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IrisRoute = IrisRouteImport.update({
  id: '/iris',
  path: '/iris',
  getParentRoute: () => rootRouteImport,
} as any)
const IocsRoute = IocsRouteImport.update({
  id: '/iocs',
  path: '/iocs',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturationRoute = FacturationRouteImport.update({
  id: '/facturation',
  path: '/facturation',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploiementRoute = DeploiementRouteImport.update({
  id: '/deploiement',
  path: '/deploiement',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertesRoute = AlertesRouteImport.update({
  id: '/alertes',
  path: '/alertes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alertes': typeof AlertesRoute
  '/architecture': typeof ArchitectureRoute
  '/assistant': typeof AssistantRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/deploiement': typeof DeploiementRoute
  '/facturation': typeof FacturationRoute
  '/integrations': typeof IntegrationsRoute
  '/iocs': typeof IocsRoute
  '/iris': typeof IrisRoute
  '/login': typeof LoginRoute
  '/outils': typeof OutilsRoute
  '/settings': typeof SettingsRoute
  '/threat-map': typeof ThreatMapRoute
  '/workflow': typeof WorkflowRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/clients/': typeof ClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alertes': typeof AlertesRoute
  '/architecture': typeof ArchitectureRoute
  '/assistant': typeof AssistantRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/deploiement': typeof DeploiementRoute
  '/facturation': typeof FacturationRoute
  '/integrations': typeof IntegrationsRoute
  '/iocs': typeof IocsRoute
  '/iris': typeof IrisRoute
  '/login': typeof LoginRoute
  '/outils': typeof OutilsRoute
  '/settings': typeof SettingsRoute
  '/threat-map': typeof ThreatMapRoute
  '/workflow': typeof WorkflowRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/clients': typeof ClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alertes': typeof AlertesRoute
  '/architecture': typeof ArchitectureRoute
  '/assistant': typeof AssistantRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/deploiement': typeof DeploiementRoute
  '/facturation': typeof FacturationRoute
  '/integrations': typeof IntegrationsRoute
  '/iocs': typeof IocsRoute
  '/iris': typeof IrisRoute
  '/login': typeof LoginRoute
  '/outils': typeof OutilsRoute
  '/settings': typeof SettingsRoute
  '/threat-map': typeof ThreatMapRoute
  '/workflow': typeof WorkflowRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/clients/': typeof ClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alertes'
    | '/architecture'
    | '/assistant'
    | '/audit'
    | '/dashboard'
    | '/deploiement'
    | '/facturation'
    | '/integrations'
    | '/iocs'
    | '/iris'
    | '/login'
    | '/outils'
    | '/settings'
    | '/threat-map'
    | '/workflow'
    | '/clients/$clientId'
    | '/clients/new'
    | '/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alertes'
    | '/architecture'
    | '/assistant'
    | '/audit'
    | '/dashboard'
    | '/deploiement'
    | '/facturation'
    | '/integrations'
    | '/iocs'
    | '/iris'
    | '/login'
    | '/outils'
    | '/settings'
    | '/threat-map'
    | '/workflow'
    | '/clients/$clientId'
    | '/clients/new'
    | '/clients'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alertes'
    | '/architecture'
    | '/assistant'
    | '/audit'
    | '/dashboard'
    | '/deploiement'
    | '/facturation'
    | '/integrations'
    | '/iocs'
    | '/iris'
    | '/login'
    | '/outils'
    | '/settings'
    | '/threat-map'
    | '/workflow'
    | '/clients/$clientId'
    | '/clients/new'
    | '/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlertesRoute: typeof AlertesRoute
  ArchitectureRoute: typeof ArchitectureRoute
  AssistantRoute: typeof AssistantRoute
  AuditRoute: typeof AuditRoute
  DashboardRoute: typeof DashboardRoute
  DeploiementRoute: typeof DeploiementRoute
  FacturationRoute: typeof FacturationRoute
  IntegrationsRoute: typeof IntegrationsRoute
  IocsRoute: typeof IocsRoute
  IrisRoute: typeof IrisRoute
  LoginRoute: typeof LoginRoute
  OutilsRoute: typeof OutilsRoute
  SettingsRoute: typeof SettingsRoute
  ThreatMapRoute: typeof ThreatMapRoute
  WorkflowRoute: typeof WorkflowRoute
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ClientsNewRoute: typeof ClientsNewRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-map': {
      id: '/threat-map'
      path: '/threat-map'
      fullPath: '/threat-map'
      preLoaderRoute: typeof ThreatMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outils': {
      id: '/outils'
      path: '/outils'
      fullPath: '/outils'
      preLoaderRoute: typeof OutilsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iris': {
      id: '/iris'
      path: '/iris'
      fullPath: '/iris'
      preLoaderRoute: typeof IrisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iocs': {
      id: '/iocs'
      path: '/iocs'
      fullPath: '/iocs'
      preLoaderRoute: typeof IocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturation': {
      id: '/facturation'
      path: '/facturation'
      fullPath: '/facturation'
      preLoaderRoute: typeof FacturationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deploiement': {
      id: '/deploiement'
      path: '/deploiement'
      fullPath: '/deploiement'
      preLoaderRoute: typeof DeploiementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertes': {
      id: '/alertes'
      path: '/alertes'
      fullPath: '/alertes'
      preLoaderRoute: typeof AlertesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlertesRoute: AlertesRoute,
  ArchitectureRoute: ArchitectureRoute,
  AssistantRoute: AssistantRoute,
  AuditRoute: AuditRoute,
  DashboardRoute: DashboardRoute,
  DeploiementRoute: DeploiementRoute,
  FacturationRoute: FacturationRoute,
  IntegrationsRoute: IntegrationsRoute,
  IocsRoute: IocsRoute,
  IrisRoute: IrisRoute,
  LoginRoute: LoginRoute,
  OutilsRoute: OutilsRoute,
  SettingsRoute: SettingsRoute,
  ThreatMapRoute: ThreatMapRoute,
  WorkflowRoute: WorkflowRoute,
  ClientsClientIdRoute: ClientsClientIdRoute,
  ClientsNewRoute: ClientsNewRoute,
  ClientsIndexRoute: ClientsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
